name: CI to Docker Hub

on:
  push:
    branches:
      - "main"
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: actions/checkout@v2
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          run: |
            echo "$PRIVATE_KEY" > openaws && chmod 600 openaws
            ssh -i openaws $USERNAME@$HOST
            sudo podman pull docker.io/vparekh17/aiserver
            sudo podman run -dp 8080:8080 --name aiserver --env-file env.list docker.io/vparekh17/aiserver