name: CI to Docker Hub

on:
  push:
    branches:
      - "main"
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        script: whoami